[project]
name = "zpp_ManagedFile"
version = "1.0.2"
description = "Système de fichier managé pour le contrôle des actions sur un fichier"
mainfile = "ManagedFile.py"
requires-python = ">=3.6"

[project.metadata]
authors = ["ZephyrOff"]
maintainers = []
readme = "README.md"
license = "MIT License"
license_file = "LICENSE"
keywords = []
classifiers = []
copyright = ""
changelog = "changelog.md"

[project.urls]
changelog = ""
homepage = "https://github.com/ZephyrOff/zpp_ManagedFile"
documentation = "https://github.com/ZephyrOff/zpp_ManagedFile"

[project.dependencies.windows]

[project.dependencies.linux]

[project.build]
packages = ["io", "tempfile", "uuid", "re"]
includes = []
excludes = []
include_files = []
optimize = 0
no_compress = false
GUI = false
icon = ""

[project.wheel]
platforms = "ALL"

[project.wheel.entry_points]
console_scripts = []
